(repository
  (url "http://snow2.s3-website-us-east-1.amazonaws.com/industria/index.scm")
  (name "r7rs industria")
  (sibling
    (name "Snow Repository")
    (url "http://snow-repository.s3-website-us-east-1.amazonaws.com/index.scm")
    (trust 1.0))
  (package
    (name ())
    (url "http://snow2.s3-website-us-east-1.amazonaws.com/industria/archive.tgz")
    (size 11287)
    (checksum (md5 "68e3513791f48fbec21c01077e549887"))
    (library
      (name (weinholt archive tar))
      (path "weinholt/archive/tar.sld")
      (version "1.0")
      (homepage "https://weinholt.se/industria/")
      (maintainers "Seth Alves <seth@hungry.com>")
      (authors "Göran Weinholt <goran@weinholt.se>")
      (description "Procedures that read Tape ARchives")
      (license mit)
      (depends (srfi 13) (srfi 19) (srfi 60) (weinholt r6rs-compatibility))))
  (package
    (name ())
    (url "http://snow2.s3-website-us-east-1.amazonaws.com/industria/bytevectors.tgz")
    (size 7703)
    (checksum (md5 "14ce1f26aa089dc7a387ab1e587cd5b5"))
    (library
      (name (weinholt bytevectors))
      (path "weinholt/bytevectors.sld")
      (version "1.0")
      (homepage "https://weinholt.se/industria/")
      (maintainers "Seth Alves <seth@hungry.com>")
      (authors "Göran Weinholt <goran@weinholt.se>")
      (description "Bytevector utilities")
      (license mit)
      (depends (srfi 60) (weinholt r6rs-compatibility))))
  (package
    (name ())
    (url "http://snow2.s3-website-us-east-1.amazonaws.com/industria/r6rs-compatibility.tgz")
    (size 4631)
    (checksum (md5 "7d1d7862371eef9fdef1079fdba3f4d0"))
    (library
      (name (weinholt r6rs-compatibility))
      (path "weinholt/r6rs-compatibility.sld")
      (version "1.0")
      (homepage "https://weinholt.se/industria/")
      (maintainers "Seth Alves <seth@hungry.com>")
      (authors "Seth Alves <seth@hungry.com>")
      (description "Bytevector utilities")
      (license mit)
      (depends (srfi 60))))
  (package
    (name ())
    (url "http://snow2.s3-website-us-east-1.amazonaws.com/industria/struct.tgz")
    (size 54295)
    (checksum (md5 "7ecd0260e2451dc3b2eddc46d6a02c2c"))
    (library
      (name (weinholt struct der))
      (path "weinholt/struct/der.sld")
      (version "1.0")
      (homepage "https://weinholt.se/industria/")
      (maintainers "Seth Alves <seth@hungry.com>")
      (authors "Göran Weinholt <goran@weinholt.se>")
      (description "Distinguished Encoding Rules (DER)")
      (license mit)
      (depends
        (srfi 1)
        (srfi 19)
        (srfi 26)
        (srfi 60)
        (weinholt r6rs-compatibility)
        (weinholt bytevectors)))
    (library
      (name (weinholt struct pack))
      (path "weinholt/struct/pack.sld")
      (version "1.0")
      (homepage "https://weinholt.se/industria/")
      (maintainers "Seth Alves <seth@hungry.com>")
      (authors "Göran Weinholt <goran@weinholt.se>")
      (description
        "Syntax for packing and unpacking C structs using bytevectors")
      (license mit)
      (depends (weinholt struct pack-aux)))
    (library
      (name (weinholt struct pack-aux))
      (path "weinholt/struct/pack-aux.sld")
      (version "1.0")
      (homepage "https://weinholt.se/industria/")
      (maintainers "Seth Alves <seth@hungry.com>")
      (authors "Göran Weinholt <goran@weinholt.se>")
      (description
        "Auxiliary library for (weinholt struct). Please don't use this library directly.")
      (license mit)
      (depends))))
